defmodule PhoenixExampleWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :phoenix_example

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_phoenix_example_key",
    signing_salt: "1rimuqZ8",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :phoenix_example,
    gzip: not code_reloading?,
    only: PhoenixExampleWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :phoenix_example
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # `RpcElixir.Plug` reads the raw request body itself, so it must reach the
  # /rpc routes unparsed. `Plug.Parsers` would otherwise consume the JSON body
  # here (before the router), leaving handlers with empty input. Skip parsing
  # for /rpc and parse everything else as usual.
  @parsers_opts Plug.Parsers.init(
                  parsers: [:urlencoded, :multipart, :json],
                  pass: ["*/*"],
                  json_decoder: Phoenix.json_library()
                )

  plug :parse_body_except_rpc

  defp parse_body_except_rpc(%Plug.Conn{path_info: ["rpc" | _]} = conn, _opts), do: conn
  defp parse_body_except_rpc(conn, _opts), do: Plug.Parsers.call(conn, @parsers_opts)

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PhoenixExampleWeb.Router
end
