// Fixture for @shikijs/vitepress-twoslash — the client the docs snippets are
// type-checked against. Generated from BasicServer.Router; do not edit.
// Regenerate: bash docs/scripts/gen-twoslash-fixture.sh
// AUTO-GENERATED by mix rpc.gen.ts — do not edit.
// Regenerate via: mix rpc.gen.ts --router YourApp.Router --out path/rpc.gen.ts
import { createClient, rpcMethod, type Client, type RpcMethod, type DomainError, type MiddlewareError } from "@elixir-ts-rpc/client";

/** Branded wire value — nominally distinct from its base type; the client does not auto-convert it. */
export type DateString = string & { readonly __brand: "DateString" };
/** Branded wire value — nominally distinct from its base type; the client does not auto-convert it. */
export type EpochMillis = number & { readonly __brand: "EpochMillis" };
/** Branded wire value — nominally distinct from its base type; the client does not auto-convert it. */
export type Int64String = string & { readonly __brand: "Int64String" };
/** Branded wire value — nominally distinct from its base type; the client does not auto-convert it. */
export type NaiveDateTimeString = string & { readonly __brand: "NaiveDateTimeString" };



export interface AuthMeInput {
}

export interface AuthMeOutput {
  id: string;
  email: string;
}

export type AuthMeError = never;

export interface UsersDeleteInput {
  id: string;
}

export interface UsersDeleteOutput {
  deleted: boolean;
}

export type UsersDeleteError = DomainError<"not_found" | "forbidden">;

export interface UsersGetInput {
  id: string;
}

export interface UsersGetOutput {
  id: string;
  email: string;
}

export type UsersGetError = DomainError<"not_found">;

export interface UsersListInput {
  filter?: { until?: EpochMillis; since?: EpochMillis; born_after?: DateString };
}

export interface UsersListOutput {
  meta: { range: { until: EpochMillis | null; since: EpochMillis | null }; generated_at: EpochMillis };
  users: ({ id: string; email: string; account_id: Int64String; birthday: DateString | null; created_at: EpochMillis; last_login_at: NaiveDateTimeString })[];
}

export type UsersListError = never;

export interface UsersUpdateInput {
  id: string;
  email: string;
}

export interface UsersUpdateOutput {
  id: string;
  email: string;
}

export type UsersUpdateError = DomainError<"not_found" | "email_taken" | "invalid_email", { field: string | null } | undefined>;

export type RpcClient = {
  auth: {
    /** [auth.ex:8](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/auth.ex#L8) — `BasicServer.Handlers.Auth.me/2` */
    me: RpcMethod<AuthMeInput, AuthMeOutput, AuthMeError | MiddlewareError<"unauthorized">>;
  };
  users: {
    /** [users.ex:115](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L115) — `BasicServer.Handlers.Users.delete/2` */
    delete: RpcMethod<UsersDeleteInput, UsersDeleteOutput, UsersDeleteError | MiddlewareError<"unauthorized">>;
    /** [users.ex:78](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L78) — `BasicServer.Handlers.Users.get/2` */
    get: RpcMethod<UsersGetInput, UsersGetOutput, UsersGetError | MiddlewareError<"unauthorized">>;
    /** [users.ex:33](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L33) — `BasicServer.Handlers.Users.list/2` */
    list: RpcMethod<UsersListInput, UsersListOutput, UsersListError | MiddlewareError<"unauthorized">>;
    /** [users.ex:93](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L93) — `BasicServer.Handlers.Users.update/2` */
    update: RpcMethod<UsersUpdateInput, UsersUpdateOutput, UsersUpdateError | MiddlewareError<"unauthorized">>;
  };
};

export function createRpcClient(opts: Parameters<typeof createClient>[0]): RpcClient {
  const client: Client = createClient(opts);
  return {
    auth: {
      /** [auth.ex:8](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/auth.ex#L8) — `BasicServer.Handlers.Auth.me/2` */
      me: rpcMethod<AuthMeInput, AuthMeOutput, AuthMeError | MiddlewareError<"unauthorized">>(client, "auth.me", ["unauthorized"]),
    },
    users: {
      /** [users.ex:115](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L115) — `BasicServer.Handlers.Users.delete/2` */
      delete: rpcMethod<UsersDeleteInput, UsersDeleteOutput, UsersDeleteError | MiddlewareError<"unauthorized">>(client, "users.delete", ["not_found", "forbidden", "unauthorized"]),
      /** [users.ex:78](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L78) — `BasicServer.Handlers.Users.get/2` */
      get: rpcMethod<UsersGetInput, UsersGetOutput, UsersGetError | MiddlewareError<"unauthorized">>(client, "users.get", ["not_found", "unauthorized"]),
      /** [users.ex:33](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L33) — `BasicServer.Handlers.Users.list/2` */
      list: rpcMethod<UsersListInput, UsersListOutput, UsersListError | MiddlewareError<"unauthorized">>(client, "users.list", ["unauthorized"]),
      /** [users.ex:93](https://github.com/ostatni5/elixir-ts-rpc/blob/main/examples/basic/server/lib/basic_server/handlers/users.ex#L93) — `BasicServer.Handlers.Users.update/2` */
      update: rpcMethod<UsersUpdateInput, UsersUpdateOutput, UsersUpdateError | MiddlewareError<"unauthorized">>(client, "users.update", ["not_found", "email_taken", "invalid_email", "unauthorized"]),
    },
  };
}
